version: "2.4"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'host.docker.internal'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://host.docker.internal'
    ports:
      - '80:80'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
    extra_hosts:
      host.docker.internal: host-gateway

volumes:
  config:
  logs:
  data:
